// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBw_0MAkuI7ZusSoXcOjwXtZ8gwIkxD9M',
    appId: '1:876419157436:web:177e57910c4c6655476fb9',
    messagingSenderId: '876419157436',
    projectId: 'tiktok-clone-tutorial',
    authDomain: 'tiktok-clone-tutorial.firebaseapp.com',
    storageBucket: 'tiktok-clone-tutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvmOb2P-OeCkl6dcGDxRTUrwcboIvEAsM',
    appId: '1:876419157436:android:85a3199fafea6dbb476fb9',
    messagingSenderId: '876419157436',
    projectId: 'tiktok-clone-tutorial',
    storageBucket: 'tiktok-clone-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4DKfJSu0uiLU6UXjuYlcy8pITLyejFpw',
    appId: '1:876419157436:ios:75b503b3957b4f9d476fb9',
    messagingSenderId: '876419157436',
    projectId: 'tiktok-clone-tutorial',
    storageBucket: 'tiktok-clone-tutorial.appspot.com',
    iosClientId: '876419157436-rmqcb051i17rc15t72sl5rb6mp1os02u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
